{% set version = "2.8" %}

package:
  name: gsl
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gsl/gsl-{{ version }}.tar.gz
  sha256: 6a99eeed15632c6354895b1dd542ed5a855c0f15d9ad1326c6fe2b2c9e423190
  patches:
    # Taken from https://github.com/ampl/gsl/tree/v2.4.0
    - patch_for_windows.diff  # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # tends to break at minor revs
    # https://abi-laboratory.pro/index.php?view=timeline&l=gsl
    - {{ pin_subpackage("gsl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - autotools_clang_conda     # [win]
    - autoconf                  # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - make                      # [unix]
  host:
    - libblas
    - libcblas
  run:

test:
  files:
    - test

  requires:
    - {{ compiler('c') }}
    - pkg-config

  commands:
    - gsl-config --prefix  # [not win]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl*.dll      exit 1   # [win]
    - ls -al $PREFIX/lib/libgsl${SHLIB_EXT}              # [not win]
    - ls -al $PREFIX/lib/libgslcblas${SHLIB_EXT}         # [not win]
    - ls -al $PREFIX/lib/libgslcblas.0.dylib             # [osx]
    - ls -al $PREFIX/lib/libgsl.*.dylib                  # [osx]
    - ls -al $PREFIX/lib/libgslcblas.so.0                # [linux]
    - ls -al $PREFIX/lib/libgsl.so.*                     # [linux]
    - pkg-config --cflags --libs gsl

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - getopt_LICENSE.txt  # [win]
  summary: GNU Scientific Library

extra:
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - ocefpaf
    - traversaro
