{% set version = "2.2.1" %}
{% set variant = "openblas" %}

package:
  name: gsl
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gsl/gsl-{{ version }}.tar.gz
  sha256: 13d23dc7b0824e1405f3f7e7d0776deee9b8f62c62860bf66e7852d402b8b024
  patches:
    # diff from source distribution to https://github.com/ampl/gsl/tree/v2.4.0
    - patch_cmake_for_windows.diff  # [win]

build:
  number: 6
  features:
    - blas_{{ variant }}  # [not win]
  run_exports:
    # tends to break at minor revs
    #    https://abi-laboratory.pro/index.php?view=timeline&l=gsl
    - {{ pin_subpackage("gsl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - cmake  # [win]
  host:
    - blas 1.1 {{ variant }}    # [not win]
    - openblas                  # [not win]
  run:
    - blas 1.1 {{ variant }}    # [not win]
    - openblas                  # [not win]

test:
  commands:
    - gsl-config --prefix  # [not win]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl.dll       exit 1   # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0
  license_file: COPYING
  summary: 'GNU Scientific Library'

extra:
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - ocefpaf
