{% set version = "2.2.1" %}
{% set variant = "openblas" %}

package:
  name: gsl
  version: {{ version }}

source:
  fn: gsl-{{ version }}.tar.gz
  url: http://ftpmirror.gnu.org/gsl/gsl-{{ version }}.tar.gz
  sha256: 13d23dc7b0824e1405f3f7e7d0776deee9b8f62c62860bf66e7852d402b8b024
  
  patches:                         # [win]
  # https://github.com/ampl/gsl/  
    - patch_cmake_for_windows.diff                   # [win]

build:
  number: 2
  features:
    - vc9    # [win and py27]
    - vc10   # [win and py34]
    - vc14   # [win and py35]
    - blas_{{ variant }}  # [unix]

requirements:
  build:
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py35]
    - blas 1.1 {{ variant }}    # [unix]
    - openblas 0.2.19|0.2.19.*  # [unix]

  run:
    - blas 1.1 {{ variant }}    # [unix]
    - openblas 0.2.19|0.2.19.*  # [unix]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - gsl-config --prefix  # [not win]
    #- conda inspect linkages -p $PREFIX gsl  # [not win]
    #- conda inspect objects -p $PREFIX gsl  # [osx]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl.dll       exit 1   # [win]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0
  license_file: COPYING
  summary: 'GNU Scientific Library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
