travis:
  secure:
    BINSTAR_TOKEN: ygjZuUbqVEd1jUsSFMRLKLEtjCbicYFmVRZ2R/qi+lEMfDFqMBIwKGJ6fqDaRTQr7efrO17zlgkPXP8xGRlY8pzX8rgs2AiqdXlPaMoOq0jNDbYS7qjL8+RxblL/281Y2w2jRUQA+aMrFvjb4cShZLukgG0l+FmstKpyuFfSBw+q1CJmMlqb3Uw3ANy76YFeyjIUCUUvA60IO99iqBOPeJJ/QQiwGBxiyUXIAdN/Sb27FHA9w7vCyF6dJeH5dhXn+s61GPUPSQrwxvk+wVUcDUSY+we3QjAVU6hBLsp79EucRc41nEoomwy0gRLZY+BUWRMNFn4Opp1vcaD0XgGdcXHW7JmyuB7eF66hW72QRB71/VDniZJGlVAfDlZsKTrfXSHw8QSRhugpOKcnqjIBQOO2a+EHmOC4Hz3WWvWoe7nETH48UtL/DNrW/iwiQywuXhCUJRqC/0QyNZBpp0WN+T+iWRV9OZ79/g9+/w7a9gPpKy7wp7QyOe1aBVAVO1R0egk40gpRinXuqYKIKPobL1k9Xlcu9vcvkD5kgA4QV3g58u+7W1zk9MKoBgXfrZxQv0JZtLgApf1qQoenNBBmMrErTnUh36k2QfoT/BsctGfHKt76KzIbku84K3ubG2xzLhHI4O1BQE0F9qt0hVUu6QQmEWy2aNb4amXytgoZn5w=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
conda_forge_output_validation: true
